name: project_strava
description: "Strava"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  go_router: ^15.1.2
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0

  geolocator: ^14.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  geolocator_android: 4.6.1

flutter:
  uses-material-design: true
